image: gitpod/workspace-full-vnc

tasks:
  - name: SETUP - btk install mamba and docker pull
    init: |
      cd /workspace
      wget "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
      bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p /workspace/mambaforge && rm Mambaforge-24.3.0-0-Linux-x86_64.sh
      /workspace/mambaforge/bin/mamba init bash

      source ${HOME}/.bashrc

      cd ./kmerbased_polishing/env/

      conda env create --name=autopolish --file=auto_polisher_env_v3.yml
      gp sync-done bundle

  - name: SETUP
    init: gp sync-await bundle
    command: |
      cd /workspace
      chmod a+x *.pl *.py
      /workspace/mambaforge/bin/mamba init bash
      source ${HOME}/.bashrc
      mamba activate autopolish
      echo "Hello there - Welcome to GitPod"

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public

workspaceLocation: "/workspace"
